// supabase/functions/initiate-payment/index.ts
//
// Called by the extension to create a Flutterwave virtual account charge.
// Returns a virtual account number + bank + amount for the user to transfer.
//
// Request body: { tx_ref, amount, email, name? }
//   tx_ref  — generated by the extension: wizard_<userId>_<timestamp>_<coupon>
//   amount  — 1000 (full price) or 500 (MAVERIC50 applied)
//   email   — user's email for the Flutterwave charge record
//
// Authorization header: Bearer <supabase_jwt>  (user must be logged in)
//
// Response:
//   { ok: true, account_number, bank_name, amount, tx_ref, expires_at }
//   { error: string }
//
// Required Supabase secret:
//   FLW_SECRET_KEY — Flutterwave secret key (Settings → API Keys → Secret key)

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL     = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const FLW_SECRET_KEY   = Deno.env.get("FLW_SECRET_KEY")!;

const CORS = {
    "Access-Control-Allow-Origin":  "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });

    // ── Verify JWT ────────────────────────────────────────────
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "MISSING_AUTH" }, 401);

    const userClient = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
        global: { headers: { Authorization: authHeader } },
    });

    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) return json({ error: "INVALID_AUTH" }, 401);

    // ── Parse body ────────────────────────────────────────────
    const body = await req.json().catch(() => ({}));
    const { tx_ref, amount, email } = body as {
        tx_ref?: string;
        amount?: number;
        email?: string;
    };

    if (!tx_ref || !amount || !email) {
        return json({ error: "MISSING_FIELDS" }, 400);
    }

    // Safety — tx_ref must belong to the calling user
    // tx_ref format: wizard_<userId>_<timestamp>_<coupon_or_none>
    const parts = tx_ref.split("_");
    if (parts[1] !== user.id) return json({ error: "TX_REF_MISMATCH" }, 403);

    // Validate amount — must be 1000 or 500 (no other values accepted)
    if (amount !== 1000 && amount !== 500) {
        return json({ error: "INVALID_AMOUNT" }, 400);
    }

    // ── Call Flutterwave — create virtual account ─────────────
    // Flutterwave Bank Transfer (virtual account) API
    // https://developer.flutterwave.com/docs/collecting-payments/bank-transfer
    let flwData: Record<string, unknown>;
    try {
        const flwRes = await fetch("https://api.flutterwave.com/v3/charges?type=bank_transfer", {
            method: "POST",
            headers: {
                Authorization:  `Bearer ${FLW_SECRET_KEY}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                tx_ref,
                amount,
                currency:    "NGN",
                email,
                fullname:    email.split("@")[0], // use email prefix as name
                phone_number: "0000000000",        // required field, dummy value
                client_ip:   "::1",
                device_fingerprint: parts[1],      // user id as fingerprint
                meta: {
                    source:  "upwork_wizard_extension",
                    user_id: user.id,
                },
            }),
        });

        flwData = await flwRes.json();
    } catch (e) {
        console.error("Flutterwave API error:", e);
        return json({ error: "FLW_UNREACHABLE" }, 502);
    }

    // ── Check response ────────────────────────────────────────
    if (flwData?.status !== "success") {
        console.error("Flutterwave initiate failed:", JSON.stringify(flwData));
        return json({
            error:   "FLW_INITIATE_FAILED",
            message: (flwData?.message as string) ?? "Unknown error from Flutterwave",
        }, 502);
    }

    const data = flwData.data as Record<string, unknown>;
    const meta = data?.meta as Record<string, unknown>;

    // ── Return account details to extension ───────────────────
    return json({
        ok:             true,
        account_number: meta?.authorization?.transfer_account as string,
        bank_name:      meta?.authorization?.transfer_bank    as string,
        amount:         data?.amount                          as number,
        tx_ref:         data?.tx_ref                          as string,
        // Account expires after a set time — show this to the user
        expires_at:     meta?.authorization?.account_expiration as string ?? null,
        note:           meta?.authorization?.transfer_note    as string ?? null,
    });
});

function json(data: unknown, status = 200) {
    return new Response(JSON.stringify(data), {
        status,
        headers: { ...CORS, "Content-Type": "application/json" },
    });
}
